#following https://github.com/databricks/koalas/pull/889/files
channels:
  - bioconda
  - conda-forge
dependencies:
  - openjdk
  - pip
  - pip:
    # In Read the Docs, seems installing 'requirements-dev.txt' seems ignored when Conda is used.
    - -r requirements.txt
    - myst-parser sphinx_rtd_theme tabulate jinja2
