#following https://github.com/databricks/koalas/pull/889/files
channels:
  - bioconda
  - conda-forge
dependencies:
  - openjdk
  - python=3.10
  - libstdcxx-ng>=13
  - libgcc-ng>=13
  - pip
  - pip:
    -  ../[all]
    - -r ./requirements.txt
    - -r ./extensions.txt
